### ISSUE TITLE
Cannot install by adding 'async-postgres' to our Gemfile

### ISSUE THREAD

**Issue by concernedrat** [socketry/async-postgres#1]
How to replicate:
* Added `gem 'async-postgres' to the project's Gemfile
* Ran `bundle install`

Got:
`Could not find gem 'async-postgres' in any of the gem sources listed in your Gemfile.`

I think async-postgres is not yet published on Rubygems

**Comment by ioquatix** [comment]
You are right. I should publish something. It was a crazy experiment.

**Comment by ioquatix** [comment]
Okay, I released `v0.1.0` from current source. I don't even know if it works. But at least you can try it out easily. Feel free to report back any issues or ideas you have.

**Comment by ioquatix** [comment]
https://rubygems.org/gems/async-postgres

**Comment by concernedrat** [comment]
Nice, thanks. Keep the hard work! this is an interesting idea and I plan to use this in a low/medium traffic API. I will report back any issues. Thanks again

**Comment by ioquatix** [comment]
If you have some metrics for latency/concurrency/processor usage, I would be most interested in a before/after analysis.
